[package]
name = "ast"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
bumpalo = "2.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
